#Lets get started with ML :Classification


In [66]:
import graphlab

In [67]:
products = graphlab.SFrame('C:\Users\hiambati\ML Projects\Course 3\week1\\amazon_baby.gl');

In [69]:
## Preview of the data.
products

Columns:
	name	str
	review	str
	rating	float

Rows: 183531

Data:
+-------------------------------+-------------------------------+--------+
|              name             |             review            | rating |
+-------------------------------+-------------------------------+--------+
|    Planetwise Flannel Wipes   | These flannel wipes are OK... |  3.0   |
|     Planetwise Wipe Pouch     | it came early and was not ... |  5.0   |
| Annas Dream Full Quilt wit... | Very soft and comfortable ... |  5.0   |
| Stop Pacifier Sucking with... | This is a product well wor... |  5.0   |
| Stop Pacifier Sucking with... | All of my kids have cried ... |  5.0   |
| Stop Pacifier Sucking with... | When the Binky Fairy came ... |  5.0   |
| A Tale of Baby's Days with... | Lovely book, it's bound ti... |  4.0   |
| Baby Tracker&reg; - Daily ... | Perfect for new parents. W... |  5.0   |
| Baby Tracker&reg; - Daily ... | A friend of mine pinned th... |  5.0   |
| Baby Tracker&reg; - Daily ... | This has been an easy way ... |  4.0   |
+-------------------------------+-------------------------------+--------+
[183531 rows x 3 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [70]:
def remove_punctuation(text):
    import string
    text.replace('n/a',"")
    return text.translate(None,string.punctuation)

products['review_clean'] = products['review'].apply(remove_punctuation)
    

In [83]:
products.head()

Columns:
	name	str
	review	str
	rating	float
	review_clean	str
	sentiment	int

Rows: 10

Data:
+-------------------------------+-------------------------------+--------+
|              name             |             review            | rating |
+-------------------------------+-------------------------------+--------+
|     Planetwise Wipe Pouch     | it came early and was not ... |  5.0   |
| Annas Dream Full Quilt wit... | Very soft and comfortable ... |  5.0   |
| Stop Pacifier Sucking with... | This is a product well wor... |  5.0   |
| Stop Pacifier Sucking with... | All of my kids have cried ... |  5.0   |
| Stop Pacifier Sucking with... | When the Binky Fairy came ... |  5.0   |
| A Tale of Baby's Days with... | Lovely book, it's bound ti... |  4.0   |
| Baby Tracker&reg; - Daily ... | Perfect for new parents. W... |  5.0   |
| Baby Tracker&reg; - Daily ... | A friend of mine pinned th... |  5.0   |
| Baby Tracker&reg; - Daily ... | This has been an easy way ... |  4.0   |
| Baby Tracker&reg; - Daily ... | I love this journal and ou... |  4.0   |
+-------------------------------+-------------------------------+--------+
+-------------------------------+-----------+
|          review_clean         | sentiment |
+-------------------------------+-----------+
| it came early and was not ... |     1     |
| Very soft and comfortable ... |     1     |
| This is a product well wor... |     1     |
| All of my kids have cried ... |     1     |
| When the Binky Fairy came ... |     1     |
| Lovely book its bound tigh... |     1     |
| Perfect for new parents We... |     1     |
| A friend of mine pinned th... |     1     |
| This has been an easy way ... |     1     |
| I love this journal and ou... |     1     |
+-------------------------------+-----------+
[10 rows x 5 columns]

In [84]:
## IGNORING ALL THE REVIEW WITH RATINGS AS 3.
products = products[products['rating']!=3]
len(products)

166752

In [85]:
products['sentiment'] = products['rating'].apply(lambda x : 1 if(x>=4) else -1 if (x<=2) else 0 )

In [86]:
products

Columns:
	name	str
	review	str
	rating	float
	review_clean	str
	sentiment	int

Rows: 166752

Data:
+-------------------------------+-------------------------------+--------+
|              name             |             review            | rating |
+-------------------------------+-------------------------------+--------+
|     Planetwise Wipe Pouch     | it came early and was not ... |  5.0   |
| Annas Dream Full Quilt wit... | Very soft and comfortable ... |  5.0   |
| Stop Pacifier Sucking with... | This is a product well wor... |  5.0   |
| Stop Pacifier Sucking with... | All of my kids have cried ... |  5.0   |
| Stop Pacifier Sucking with... | When the Binky Fairy came ... |  5.0   |
| A Tale of Baby's Days with... | Lovely book, it's bound ti... |  4.0   |
| Baby Tracker&reg; - Daily ... | Perfect for new parents. W... |  5.0   |
| Baby Tracker&reg; - Daily ... | A friend of mine pinned th... |  5.0   |
| Baby Tracker&reg; - Daily ... | This has been an easy way ... |  4.0   |
| Baby Tracker&reg; - Daily ... | I love this journal and ou... |  4.0   |
+-------------------------------+-------------------------------+--------+
+-------------------------------+-----------+
|          review_clean         | sentiment |
+-------------------------------+-----------+
| it came early and was not ... |     1     |
| Very soft and comfortable ... |     1     |
| This is a product well wor... |     1     |
| All of my kids have cried ... |     1     |
| When the Binky Fairy came ... |     1     |
| Lovely book its bound tigh... |     1     |
| Perfect for new parents We... |     1     |
| A friend of mine pinned th... |     1     |
| This has been an easy way ... |     1     |
| I love this journal and ou... |     1     |
+-------------------------------+-----------+
[166752 rows x 5 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [87]:
train_data,test_data = products.random_split(.8,seed=1)
print len(train_data)
print len(test_data)

133416
33336


###Using Skitlearn to analyze the words present in the training data and use the same words in the feature to make the word vectors

In [88]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(token_pattern=r'\b\w+\b')
     # Use this token pattern to keep single-letter words
# First, learn vocabulary from the training data and assign columns to words
train_data['word_count'] = graphlab.text_analytics.count_words(train_data['review_clean'])
# Then convert the training data into a sparse matrix
train_matrix = vectorizer.fit_transform(train_data['review_clean'])
# Second, convert the test data into a sparse matrix, using the same word-column mapping
test_matrix = vectorizer.transform(test_data['review_clean'])

In [92]:
from sklearn.linear_model import LogisticRegression
logisticReg.get_params

<bound method LogisticRegression.get_params of LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)>

In [93]:

logisticReg = LogisticRegression()
sentiment_model = logisticReg.fit(train_matrix,train_data['sentiment'])

In [96]:
coeff_arr = sentiment_model.coef_
print coeff_arr
print coeff_arr.size
count=0
counter=0
for i in range(coeff_arr.size):
    if(coeff_arr[0][i]>=0):
        count =count+1
    else:
        counter = counter+1
        
print count
print counter       

[[ -1.23623881e+00   2.11395655e-04   2.58652579e-02 ...,   1.13668435e-02
    3.21471115e-03  -7.23017202e-05]]
121712
85782
35930


In [97]:
sample_test_data = test_data[10:13]
print sample_test_data

+-------------------------------+-------------------------------+--------+
|              name             |             review            | rating |
+-------------------------------+-------------------------------+--------+
|   Our Baby Girl Memory Book   | Absolutely love it and all... |  5.0   |
| Wall Decor Removable Decal... | Would not purchase again o... |  2.0   |
| New Style Trailing Cherry ... | Was so excited to get this... |  1.0   |
+-------------------------------+-------------------------------+--------+
+-------------------------------+-----------+
|          review_clean         | sentiment |
+-------------------------------+-----------+
| Absolutely love it and all... |     1     |
| Would not purchase again o... |     -1    |
| Was so excited to get this... |     -1    |
+-------------------------------+-----------+
[3 rows x 5 columns]



In [98]:
sample_test_data[0]['review']

'Absolutely love it and all of the Scripture in it.  I purchased the Baby Boy version for my grandson when he was born and my daughter-in-law was thrilled to receive the same book again.'

In [99]:
import numpy as np
sample_test_matrix = vectorizer.transform(sample_test_data['review_clean'])
scores = sentiment_model.decision_function(sample_test_matrix)
print scores

[  5.59985274  -3.13291898 -10.42127865]


In [100]:
def get_predictions(predicts):
    result = [0]*predicts.size
    for i in range(predicts.size):
        if(predicts[i] > 0):
            result[i] = +1
        else:
            result[i] = -1
    
    return result,np.array(result)
    

In [102]:
(predictions,predictions_np) = get_predictions(scores)
print predictions ## this is a numpy array 
#print sentiment_model.predict(sample_test_matrix)


[1, -1, -1]


In [103]:
## NOW CALCULATING THE PROBABILITIES BY USING LOGIT MODEL (SIMODAL) I.E.,1/1-(E^(-x))
def probability_check(score):
    results = [0]*score.size
    import math
    for i in range(score.size):
        results[i] = (1/(1+math.exp(-1*score[i])))
        
    return np.array(results)

In [104]:
probability = probability_check(scores)

In [105]:
# PROBABILITIES CALCULATED USING THE SIMODAL OR LOGIT MODEL FOR LOGISTIC REGRESSION 
probability

array([  9.96315220e-01,   4.17696186e-02,   2.97908743e-05])

In [106]:
# PROBABILITIES CALCUATED USING SENTIMENTAL MODEL.
print sentiment_model.predict_proba(sample_test_matrix)

[[  3.68478048e-03   9.96315220e-01]
 [  9.58230381e-01   4.17696186e-02]
 [  9.99970209e-01   2.97908743e-05]]


###Now we calculate on the entire test data 

In [107]:
test_data_matrix = vectorizer.transform(test_data['review_clean'])
train_data_matrix = vectorizer.transform(train_data['review_clean'])
scores_train = sentiment_model.decision_function(train_matrix)
scores_test = sentiment_model.decision_function(test_data_matrix)
print scores_test

[  1.25934826  14.10916572   2.6582247  ...,  12.08727214  12.8571617
   3.92614929]


In [24]:
probabilities_test = probability_check(scores_test)
test_data['Probabilities'] = probabilities_test
type(probabilities_test)

numpy.ndarray

In [25]:
#Most Positive reviews
np.sort(probabilities_test)[::-1][0:20]
#sorted(probabilities_test,reverse=True)


array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [26]:
test_data.sort('Probabilities',ascending = False).print_rows(num_rows =20)

+-------------------------------+-------------------------------+--------+
|              name             |             review            | rating |
+-------------------------------+-------------------------------+--------+
| Evenflo 6 Pack Classic Gla... | It's always fun to write a... |  5.0   |
| Fisher-Price Cradle 'N Swi... | My husband and I cannot st... |  5.0   |
| Graco Pack 'n Play Element... | My husband and I assembled... |  4.0   |
| Diono RadianRXT Convertibl... | I bought this seat for my ... |  5.0   |
| Simple Wishes Hands-Free B... | I just tried this hands fr... |  5.0   |
| Mamas &amp; Papas 2014 Urb... | After much research I purc... |  4.0   |
| Baby Jogger City Mini GT S... | Amazing, Love, Love, Love ... |  5.0   |
| Britax 2012 B-Agile Stroll... | [I got this stroller for m... |  4.0   |
| Freemie Hands-Free Conceal... | I absolutely love this pro... |  5.0   |
| P'Kolino Silly Soft Seatin... | I've purchased both the P'... |  4.0   |
| Roan Rocco Classic Pram

In [28]:
#Most PNegative reviews
np.sort(probabilities_test)[::1][0:20]

array([  9.14058112e-16,   1.90522053e-15,   8.29368105e-14,
         1.52467986e-13,   1.70961843e-13,   4.88520136e-13,
         3.33019122e-11,   4.27868876e-11,   8.93839662e-11,
         1.06731131e-10,   4.29862210e-10,   4.74639356e-10,
         6.17307408e-10,   6.58373381e-10,   7.85112403e-10,
         8.02078787e-10,   9.10157280e-10,   1.10331074e-09,
         1.62287925e-09,   1.69392295e-09])

In [29]:
test_data.sort('Probabilities',ascending = True).print_rows(num_rows =20)

+-------------------------------+-------------------------------+--------+
|              name             |             review            | rating |
+-------------------------------+-------------------------------+--------+
| Fisher-Price Ocean Wonders... | We have not had ANY luck w... |  2.0   |
| Levana Safe N'See Digital ... | This is the first review I... |  1.0   |
| Safety 1st Exchangeable Ti... | I thought it sounded great... |  1.0   |
| Adiri BPA Free Natural Nur... | I will try to write an obj... |  2.0   |
| VTech Communications Safe ... | This is my second video mo... |  1.0   |
| The First Years True Choic... | Note: we never installed b... |  1.0   |
| Safety 1st High-Def Digita... | We bought this baby monito... |  1.0   |
| Cloth Diaper Sprayer--styl... | I bought this sprayer out ... |  1.0   |
| Motorola Digital Video Bab... | DO NOT BUY THIS BABY MONIT... |  1.0   |
| Philips AVENT Newborn Star... | It's 3am in the morning an... |  1.0   |
| Cosco Alpha Omega Elite

Computing Accuracy 

In [30]:
test_data

Columns:
	name	str
	review	str
	rating	float
	review_clean	str
	sentiment	int
	Probabilities	float

Rows: 33336

Data:
+-------------------------------+-------------------------------+--------+
|              name             |             review            | rating |
+-------------------------------+-------------------------------+--------+
| Baby Tracker&reg; - Daily ... | This has been an easy way ... |  4.0   |
| Baby Tracker&reg; - Daily ... | I love this journal and ou... |  4.0   |
| Nature's Lullabies First Y... | I love this little calende... |  5.0   |
| Nature's Lullabies Second ... | I had a hard time finding ... |  5.0   |
|  Lamaze Peekaboo, I Love You  | One of baby's first and fa... |  4.0   |
|  Lamaze Peekaboo, I Love You  | My son loved this book as ... |  5.0   |
|  Lamaze Peekaboo, I Love You  | Our baby loves this book &... |  5.0   |
| SoftPlay Giggle Jiggle Fun... | This bear is absolutely ad... |  2.0   |
| SoftPlay Peek-A-Boo Where'... | I bought two for recent ba... |  5.0   |
| Baby's First Year Undated ... | I searched high and low fo... |  5.0   |
+-------------------------------+-------------------------------+--------+
+-------------------------------+-----------+----------------+
|          review_clean         | sentiment | Probabilities  |
+-------------------------------+-----------+----------------+
| This has been an easy way ... |     1     | 0.778913893914 |
| I love this journal and ou... |     1     | 0.999999254467 |
| I love this little calende... |     1     | 0.934516109658 |
| I had a hard time finding ... |     1     | 0.999977922896 |
| One of babys first and fav... |     1     | 0.980149706723 |
| My son loved this book as ... |     1     | 0.999951811798 |
| Our baby loves this book  ... |     1     | 0.998726826348 |
| This bear is absolutely ad... |     -1    | 0.805491764574 |
| I bought two for recent ba... |     1     | 0.998468031312 |
| I searched high and low fo... |     1     | 0.997299494041 |
+-------------------------------+-----------+----------------+
[33336 rows x 6 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [31]:
def probability_match(prob):
    if(prob>=0.5):
        return +1
    else:
        return -1
        

In [32]:
test_data['estimated_sent'] =test_data['Probabilities'].apply(probability_match)

In [33]:
correct_classified  = test_data[test_data['sentiment'] == test_data['estimated_sent']]

In [34]:
accuracy = (len(correct_classified)*1.0/ len(test_data))
print accuracy

0.932265418766


## Does a higher accuracy value on the training_data always imply that the classifier is better?

In [35]:
#No ,in thus case there will be a overfitting in the model.Thus it is not poreffered to have a huge accuracy .A decent accuracy is 
# needed rather than 100 % accuracy.


In [36]:
# Here we defined the specific words which are important for our analysis.If not particular we can use a string pattern to
# recognise the words and use for analysis
significant_words = ['love', 'great', 'easy', 'old', 'little', 'perfect', 'loves', 
      'well', 'able', 'car', 'broke', 'less', 'even', 'waste', 'disappointed', 
      'work', 'product', 'money', 'would', 'return']

In [38]:
vector_word_subset = CountVectorizer(vocabulary = significant_words) # set the words for vectorizer 
# fit the train words,so that same set of words can be used for test set too 
train_matrix_vector_subset = vector_word_subset.fit_transform(train_data['review_clean']) 
# testing the same wordset on test data 
test_matrix_vector_subset = vector_word_subset.transform(test_data['review_clean'])

In [39]:
simple_model= logisticReg.fit(train_matrix_vector_subset,train_data['sentiment'])

In [40]:
simple_model_coef_table = graphlab.SFrame({'word':significant_words,
                                         'coefficient':simple_model.coef_.flatten()})

In [41]:
simple_model_coef_table.sort('coefficient',ascending=False)

Columns:
	coefficient	float
	word	str

Rows: 20

Data:
+-----------------+---------+
|   coefficient   |   word  |
+-----------------+---------+
|  1.67307389259  |  loves  |
|  1.50981247669  | perfect |
|  1.36368975931  |   love  |
|  1.19253827349  |   easy  |
|  0.943999590572 |  great  |
|  0.520185762718 |  little |
|  0.503760457767 |   well  |
|  0.190908572065 |   able  |
|  0.085512779463 |   old   |
| 0.0588546711524 |   car   |
+-----------------+---------+
[20 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [42]:
len(simple_model_coef_table[simple_model_coef_table['coefficient']>0])

10

In [43]:
##Accuracy of simple model 
test_data['simple_model_prob'] = probability_check(simple_model.decision_function(test_matrix_vector_subset))
test_data['simple_model_sentiment']=test_data['simple_model_prob'].apply(probability_match)
sm_acc= len(test_data[test_data['simple_model_sentiment']==test_data['sentiment']])*1.0/len(test_data)
print "Test data accuracy on Simple Model :", sm_acc

Test data accuracy on Simple Model : 0.869360451164


In [44]:
train_data['simple_model_prob'] = probability_check(simple_model.decision_function(train_matrix_vector_subset))
train_data['simple_model_sentiment'] = train_data['simple_model_prob'].apply(probability_match)
sm_acc_train = len(train_data[train_data['simple_model_sentiment']==train_data['sentiment']])*1.0/len(train_data)
print "Train data accuracy on Simple Model :", sm_acc_train

Train data accuracy on Simple Model : 0.866822570007


In [45]:
# Now doing the same thing for Sentimental Model  using test_data
test_data['sentiment_model_sentiment'] = test_data['Probabilities'].apply(probability_match)
s_acc_test = len(test_data[test_data['sentiment_model_sentiment']==test_data['sentiment']])*1.0/len(test_data)
print "Train data accuracy on Simple Model :", s_acc_test

Train data accuracy on Simple Model : 0.932265418766


In [46]:
train_data['Sentiment_model_prob'] = probability_check(scores_train)
train_data['Sentiment_model_sentiment'] = train_data['Sentiment_model_prob'].apply(probability_match)
s_acc_train = len(train_data[train_data['Sentiment_model_sentiment']==train_data['sentiment']])*1.0/len(train_data)
print "Train data accuracy on Simple Model :", s_acc_train

Train data accuracy on Simple Model : 0.967702524435


## Baseline: Majority class prediction

In [47]:
num_positive  = (test_data['sentiment'] == +1).sum()
num_negative = (test_data['sentiment'] == -1).sum()
print num_positive
print num_negative

28095
5241


In [48]:
mcp = num_positive*1.0/(num_negative+num_positive)
print mcp

0.842782577394


In [58]:
sentiment_model_words_table = graphlab.SFrame({'word':significant_words,
                                         'coefficient':sentiment_model.coef_.flatten()})

In [59]:
sentiment_model_words_table

Columns:
	coefficient	float
	word	str

Rows: 20

Data:
+-----------------+---------+
|   coefficient   |   word  |
+-----------------+---------+
|  1.36368975931  |   love  |
|  0.943999590572 |  great  |
|  1.19253827349  |   easy  |
|  0.085512779463 |   old   |
|  0.520185762718 |  little |
|  1.50981247669  | perfect |
|  1.67307389259  |  loves  |
|  0.503760457767 |   well  |
|  0.190908572065 |   able  |
| 0.0588546711524 |   car   |
+-----------------+---------+
[20 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.